name: trafficlight-simulation-minimal
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - matplotlib
  - networkx
  - pgmpy
  - pip
  - pip:
      - opt_einsum
      - pyro-ppl
